// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: pf_calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputNumber int64 `protobuf:"varint,1,opt,name=input_number,json=inputNumber,proto3" json:"input_number,omitempty"`
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pf_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pf_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_pf_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetInputNumber() int64 {
	if x != nil {
		return x.InputNumber
	}
	return 0
}

type PrimeFactorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PrimeFactorResponse) Reset() {
	*x = PrimeFactorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pf_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeFactorResponse) ProtoMessage() {}

func (x *PrimeFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pf_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeFactorResponse.ProtoReflect.Descriptor instead.
func (*PrimeFactorResponse) Descriptor() ([]byte, []int) {
	return file_pf_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeFactorResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_pf_calculator_proto protoreflect.FileDescriptor

var file_pf_calculator_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x66, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x66, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x32, 0x0a, 0x0d,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x2d, 0x0a, 0x13, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0x7b, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x0f, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x50, 0x5a, 0x4e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x64, 0x65, 0x6b, 0x75,
	0x6e, 0x6c, 0x65, 0x44, 0x61, 0x6c, 0x6c, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pf_calculator_proto_rawDescOnce sync.Once
	file_pf_calculator_proto_rawDescData = file_pf_calculator_proto_rawDesc
)

func file_pf_calculator_proto_rawDescGZIP() []byte {
	file_pf_calculator_proto_rawDescOnce.Do(func() {
		file_pf_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_pf_calculator_proto_rawDescData)
	})
	return file_pf_calculator_proto_rawDescData
}

var file_pf_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pf_calculator_proto_goTypes = []interface{}{
	(*NumberRequest)(nil),       // 0: primefactorcalculator.NumberRequest
	(*PrimeFactorResponse)(nil), // 1: primefactorcalculator.PrimeFactorResponse
}
var file_pf_calculator_proto_depIdxs = []int32{
	0, // 0: primefactorcalculator.PrimeFactorService.PrimeFactorCalc:input_type -> primefactorcalculator.NumberRequest
	1, // 1: primefactorcalculator.PrimeFactorService.PrimeFactorCalc:output_type -> primefactorcalculator.PrimeFactorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pf_calculator_proto_init() }
func file_pf_calculator_proto_init() {
	if File_pf_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pf_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pf_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeFactorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pf_calculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pf_calculator_proto_goTypes,
		DependencyIndexes: file_pf_calculator_proto_depIdxs,
		MessageInfos:      file_pf_calculator_proto_msgTypes,
	}.Build()
	File_pf_calculator_proto = out.File
	file_pf_calculator_proto_rawDesc = nil
	file_pf_calculator_proto_goTypes = nil
	file_pf_calculator_proto_depIdxs = nil
}
